server:
  port: 8099

spring:
  application:
    name: power-reliability-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  level:
    com.powerreliability: info
